color = input("Please enter any color : ")
plural_noun = input("Please enter plural_noun : ")
celebrity = input("Please enter any celebrity name : ")
print("Roses are " + color)
print(plural_noun + " are blue")
print("I love " + celebrity)